In [3]:
import torch
print(torch.__version__)

2.5.1


/Users/radhika/Desktop/Personal/Interview related content/NLP/Introduction_to_PyTorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [4]:
if torch.cuda.is_available():
    print('GPU is available')
    print(torch.cuda.get_device_name(0))
else:
    print('GPU is not available')

GPU is not available


### Creating Tensors

In [ ]:
a = torch.empty(2,3)
print("Empty", a, type(a))

b = torch.zeros(2,3)
print("Zeroes", b)

c = torch.ones(2,3)
print("Ones", c)

d = torch.rand(2,3)
print("Random from 0 to 1", d)
#reserves memory for this tensor with values at that memory location

Empty tensor([[0., 0., 0.],
        [0., 0., 0.]]) <class 'torch.Tensor'>
Zeroes tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random from -1 to 1 tensor([[0.7663, 0.8685, 0.8751],
        [0.7308, 0.1706, 0.9154]])


In [8]:
torch.manual_seed(42)
e = torch.randn(2,3)
print("Random from normal distribution", e)

f = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("From list", f)

Random from normal distribution tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
From list tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
torch.arange(0, 10, 2)
print("Range", torch.arange(0, 10, 2))

#Using linspace
torch.linspace(0, 10, 5)
print("Linspace", torch.linspace(0, 10, 5))

# Using eye | Identity matrix
torch.eye(3)
print("Identity matrix", torch.eye(3))

# Using full | All values are same
torch.full((2,3), 42)
print("Full", torch.full((2,3), 42))

Range tensor([0, 2, 4, 6, 8])
Linspace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Identity matrix tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Full tensor([[42, 42, 42],
        [42, 42, 42]])


### Tensor Shapes

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)

## Using empty_like, zeros_like, ones_like, rand_like
y = torch.empty_like(x)
print("Empty_like", y)

z = torch.zeros_like(x)
print("Zeros_like", z)

o = torch.ones_like(x)
print("Ones_like", o)

r = torch.rand_like(x, dtype=torch.float32)
print("Rand_like", r)

torch.Size([2, 3])
Empty_like tensor([[0, 0, 0],
        [0, 0, 0]])
Zeros_like tensor([[0, 0, 0],
        [0, 0, 0]])
Ones_like tensor([[1, 1, 1],
        [1, 1, 1]])
Rand_like tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


### Tensor Data Types

In [12]:
x.dtype

torch.int64

In [16]:
## assign dtype
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(x, x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32


### Mathematical Operations

In [17]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

## Addition
c = a + b

## Subtraction
d = a - b

## Multiplication
e = a * b

## Division
f = a / b

## Matrix Multiplication(Mat Mul)
g = a @ b
print("Mat Mul", g)

## Element wise multiplication
h = a.mul(b)
print("Element wise multiplication", h)

Mat Mul tensor([[0.1452, 0.3908],
        [0.1265, 0.3432]])
Element wise multiplication tensor([[0.0792, 0.5218],
        [0.0284, 0.1189]])


### Reduction Operation

In [20]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("All", torch.sum(a))

## Sum along axis
print("Sum along axis 0", torch.sum(a, axis=0))

print("Sum along axis 1", torch.sum(a, axis=1))


All tensor(21.)
Sum along axis 0 tensor([5., 7., 9.])
Sum along axis 1 tensor([ 6., 15.])


In [21]:
## Mean
print("Mean", torch.mean(a))

Mean tensor(3.5000)


In [24]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

## Mat Mul
a@b.T

## Element wise multiplication
a.mul(b)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

### Inplace operations

In [25]:
## inplace operations
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("Before", a)

a.add_(2)
print("After", a)

Before tensor([[1., 2., 3.],
        [4., 5., 6.]])
After tensor([[3., 4., 5.],
        [6., 7., 8.]])


In [26]:
## copying tensors
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
b = a.clone()
print("Before", a)
print("Before", b)

a.add_(2)
print("After", a)
print("After", b)

Before tensor([[1., 2., 3.],
        [4., 5., 6.]])
Before tensor([[1., 2., 3.],
        [4., 5., 6.]])
After tensor([[3., 4., 5.],
        [6., 7., 8.]])
After tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor Operations on GPU

In [27]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

## Create tensor on GPU
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device)
print(a)    

## Move tensor to GPU
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(a)

a = a.to(device)
print(a)

cpu
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [29]:
b = torch.rand(2, 3, 4)
b.shape

torch.Size([2, 3, 4])

In [30]:
b.permute(1, 0, 2).shape

torch.Size([3, 2, 4])

In [31]:
## UnSqueeze

c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [32]:
d = torch.rand(1, 226, 226, 3)
d.squeeze(0).shape

torch.Size([226, 226, 3])

### Numpy vs Tensorflow

In [ ]:
import numpy as np

a = torch.tensor([1, 2, 3])
b = a.numpy()
print(b, type(b))

a = np.array([1, 2, 3])
b = torch.from_numpy(a)
print(b, type(b))